# Generated by Django 3.2.20 on 2023-09-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=50)),
                ('Teacher', models.CharField(max_length=50)),
                ('Period1', models.CharField(max_length=50)),
                ('Period2', models.CharField(max_length=50)),
                ('Period3', models.CharField(max_length=50)),
                ('Period4', models.CharField(max_length=50)),
                ('Period5', models.CharField(max_length=50)),
                ('Period6', models.CharField(max_length=50)),
                ('Period7', models.CharField(max_length=50)),
            ],
        ),
    ]
