# Generated by Django 3.2.20 on 2023-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=20)),
                ('Sec', models.CharField(max_length=10)),
                ('Contact', models.CharField(max_length=15)),
            ],
        ),
    ]
