# Generated by Django 3.2.20 on 2023-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updatedby', models.CharField(max_length=20)),
                ('USN', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
    ]
