# Generated by Django 3.2.20 on 2023-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_faculty_messagestable'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestable',
            name='Reason',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
