# Generated by Django 3.2.20 on 2023-10-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_messagestable_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('By', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
