# Generated by Django 3.2.20 on 2023-10-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=20)),
                ('To', models.CharField(max_length=20)),
                ('Reason', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
