# Generated by Django 3.2.20 on 2023-10-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjectcode', models.CharField(max_length=10)),
                ('Semester', models.CharField(max_length=10)),
            ],
        ),
    ]
