# Generated by Django 3.2.20 on 2023-10-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Semester',
            field=models.CharField(default=7, max_length=3),
            preserve_default=False,
        ),
    ]
