# Generated by Django 3.2.20 on 2023-10-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_students_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('SubjectName', models.CharField(max_length=20)),
                ('Internal', models.CharField(max_length=10)),
                ('Input', models.BooleanField(default=True)),
                ('Marks', models.CharField(max_length=10)),
            ],
        ),
    ]
